### PR TITLE
Fix for https://github.com/techservicesillinois/awscli-login/issues/41

### PR DESCRIPTION
**Pull request by lhoekenga**
Taken from Cornell:
https://github.com/techservicesillinois/awscli-login/compare/master...CU-CommunityApps:master

### CODE REVIEW

**Comment by kwessel** [comment]
@ddriddle, we'll need this merged in in the next month, or it's going to hold up our move of our own IdP to AWS as the Dockerized IdP is running version 4. As more IdP operators outside of Illinois move to version 4 (version 3 goes EOL at the end of the calendar year, and a lot of folks are upgrading right now), this will impact more implementations of this plugin.

**Comment by JonRoma** [comment]
@kwessel, will V3 Shibboleth IdP accept the timestamp with the addition of the timestamp?

**Review by edthedev — APPROVED** [review]
Looks good to me. If my read of the issue is correct, this change is valid both for the current version and future compatibility.

**Comment by edthedev** [comment]
@ddriddle Please take a look at this when you have a few minutes. Thanks!

**Comment by edthedev** [comment]
And @lhoekenga Thanks for the pull request!

**Review by JonRoma — APPROVED** [review]

**Comment by JonRoma** [comment]
@ddriddle, @edthedev and I (the latter belatedly) merged it into master. Please upload to PyPI as soon as you can.

**Pull request merged**
