### PR TITLE
Add integration tests

### PR DESCRIPTION
**Pull request by ddriddle**
These integration tests are for aws v1 but should work with aws v2. This PR is ready to merge after review. Unfortently, the tests are failing due to caching issues... (https://github.com/techservicesillinois/cache-validation/issues/23)

### CODE REVIEW

**Review by edthedev — APPROVED** [review]
Looks good.

Let's do a team demo of `bats` so we all know the basics of using it to test command line tools.

**Comment by mpitcel** [comment]
Are we OK to move forward with merging, etc. if the tests are not all passing?

**Review by mpitcel — APPROVED** [review]

**Comment by edthedev** [comment]
During our collaboration this morning, we were about to temporarily disable the 'validate wheel cache', to allow it to reach an unrelated issue that we want to tackle, but we ran out of time.

**Comment by edthedev** [comment]
The cache validation POST error we're seeing is a known (intermittent) issue we have documented over here: https://github.com/techservicesillinois/cache-validation/issues/23

**Comment by mpitcel** [comment]
> The cache validation POST error we're seeing is a known (intermittent) issue we have documented over here: [techservicesillinois/cache-validation#23](https://github.com/techservicesillinois/cache-validation/issues/23)

Can this error then be ignored for now and not taken into account for this PR?

**Comment by mpitcel** [comment]
FYI This PR will need to be updated from the `master` branch before it can be merged

**Review by mpitcel — APPROVED** [review]

**Review by edthedev — APPROVED** [review]

**Pull request merged**
